//! Autogenerated weights for `pallet_supersig`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight as DbWeight, Weight},
};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn mint() -> Weight;
	fn change_fee_percent() -> Weight;
}

/// Weight functions for `pallet_mint_with_fee`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: MintWithfee FeePercent (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn mint() -> Weight {
		(100_721_000u64)
			.saturating_add(T::DbWeight::get().reads(3u64))
			.saturating_add(T::DbWeight::get().writes(2u64))
	}

	// Storage: MintWithfee FeePercent (r:0 w:1)
	fn change_fee_percent() -> Weight {
		(25_050_000u64).saturating_add(T::DbWeight::get().writes(1u64))
	}
}

