
//! Autogenerated weights for `pallet_supersig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-21, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ubuntu-s-kabocha-01-1627404188468-s-2vcpu-4gb-intel-lon1-01`, CPU: `DO-Regular`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/parachain-collator
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_supersig
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// runtime/src/weights/pallet_supersig.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_supersig`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_supersig::WeightInfo for WeightInfo<T> {
	// Storage: Supersig NonceSupersig (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Supersig TotalDeposit (r:1 w:1)
	/// The range of component `z` is `[0, 9]`.
	/// The range of component `z` is `[0, 9]`.
	fn create_supersig(z: u32, ) -> Weight {
		(222_276_000 as Weight)
			// Standard Error: 194_000
			.saturating_add((16_591_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(z as Weight)))
	}
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: Supersig NonceCall (r:1 w:1)
	// Storage: Supersig Calls (r:0 w:1)
	/// The range of component `z` is `[0, 100000]`.
	/// The range of component `z` is `[0, 100000]`.
	fn submit_call(z: u32, ) -> Weight {
		(152_646_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:0)
	// Storage: Supersig MembersVotes (r:1 w:1)
	// Storage: Supersig Members (r:1 w:0)
	// Storage: Supersig Votes (r:1 w:1)
	fn approve_call() -> Weight {
		(171_355_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Supersig MembersVotes (r:0 w:1)
	// Storage: Supersig Votes (r:0 w:1)
	fn remove_call() -> Weight {
		(174_681_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig TotalDeposit (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `z` is `[0, 10]`.
	/// The range of component `z` is `[0, 10]`.
	fn add_members(z: u32, ) -> Weight {
		(142_859_000 as Weight)
			// Standard Error: 293_000
			.saturating_add((22_459_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(z as Weight)))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig TotalDeposit (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `z` is `[0, 10]`.
	/// The range of component `z` is `[0, 10]`.
	fn remove_members(z: u32, ) -> Weight {
		(142_372_000 as Weight)
			// Standard Error: 323_000
			.saturating_add((29_382_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(z as Weight)))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig TotalDeposit (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Supersig Calls (r:1 w:0)
	// Storage: Supersig Members (r:0 w:3)
	// Storage: Supersig NonceCall (r:0 w:1)
	fn delete_supersig() -> Weight {
		(330_578_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	// Storage: Supersig TotalDeposit (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn leave_supersig() -> Weight {
		(174_853_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
}
